[package]
name = "rust_geometric"
version = "0.1.0"
authors = ["merden"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.3.0"
petgraph = "0.5.0"
ndarray = "0.14.0"
snafu = "0.6.10"